type: dict
required_keys:
    short_title:
        type: string
    long_title:
        type: string
    navigation:
        type: list
        element_schema:
            type: dict
            required_keys:
                text:
                    type: string
                url:
                    type: string
